# Generated by Django 4.0.6 on 2022-07-08 05:43

import django.core.validators
from django.db import migrations, models
import django_jsonform.models.fields
import thebaeoom_backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '저자', 'verbose_name_plural': '저자'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '도서', 'verbose_name_plural': '도서'},
        ),
        migrations.AlterField(
            model_name='author',
            name='blog_link',
            field=models.TextField(verbose_name='블로그 링크'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cafe_link',
            field=models.TextField(verbose_name='카페 링크'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(verbose_name='저자 소개'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=15, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='author',
            name='sns_link',
            field=models.TextField(verbose_name='SNS 링크'),
        ),
        migrations.AlterField(
            model_name='author',
            name='youtube_link',
            field=models.TextField(verbose_name='유튜브 링크'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book', to='book.author', verbose_name='저자'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookstore_link',
            field=django_jsonform.models.fields.JSONField(verbose_name='구매 링크'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=15, verbose_name='분야'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to=thebaeoom_backend.utils.get_file_upload_path, verbose_name='표지'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='도서 소개'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_ebook',
            field=models.BooleanField(default=False, verbose_name='eBook 여부'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.PositiveIntegerField(verbose_name='페이지'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubDate',
            field=models.DateField(verbose_name='발행일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=15, verbose_name='출판사'),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.TextField(verbose_name='사이즈(규격)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='table_of_contents',
            field=django_jsonform.models.fields.JSONField(verbose_name='목차'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
