# Generated by Django 4.0.6 on 2022-07-08 05:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='작가 소개'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='도서 소개'),
        ),
    ]
