# Generated by Django 4.0.6 on 2022-07-08 05:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_description_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='table_of_contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='목차'),
        ),
    ]
