# Generated by Django 4.0.6 on 2022-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_table_of_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False, unique=True, verbose_name='ISBN'),
        ),
    ]
