# Generated by Django 4.0.6 on 2022-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubDate',
            field=models.DateField(help_text='2000-00-00 형식', verbose_name='발행일'),
        ),
    ]
