# Generated by Django 4.0.6 on 2022-07-08 04:08

import ckeditor_uploader.fields
from django.db import migrations, models
import thebaeoom_backend.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTICE', '공지사항'), ('FILE', '자료실')], max_length=10)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveIntegerField(default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('file', models.FileField(upload_to=thebaeoom_backend.utils.get_file_upload_path)),
            ],
        ),
    ]
