# Generated by Django 4.0.6 on 2022-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_partnershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='제휴제안서 첨부'),
        ),
    ]
