# Generated by Django 4.0.6 on 2022-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_partnershiprequest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiprequest',
            name='status',
            field=models.IntegerField(choices=[(0, '접수'), (1, '처리 중'), (2, '처리 완료')], default=0, help_text='제휴문의에 대한 내부 처리 상태 관리용입니다.', verbose_name='처리 상태'),
        ),
    ]
