# Generated by Django 4.0.6 on 2022-07-08 08:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_pubdate'),
        ('board', '0005_alter_partnershiprequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershiprequest',
            options={'verbose_name': '제휴 문의', 'verbose_name_plural': '제휴 문의'},
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='company_link',
            field=models.TextField(help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', verbose_name='홈페이지'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='company_name',
            field=models.CharField(help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', max_length=15, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', verbose_name='제휴 제안 내용'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='file',
            field=models.FileField(blank=True, help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', null=True, upload_to='', verbose_name='제휴 제안서 첨부'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='manager_mail',
            field=models.EmailField(help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', max_length=254, verbose_name='담당자 이메일'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='manager_name',
            field=models.CharField(help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', max_length=15, verbose_name='담당자명'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='manager_phone',
            field=models.CharField(help_text='접수된 제휴 문의는 처리 상태 외의 정보 수정이 불가능합니다.', max_length=11, verbose_name='담당자 연락처'),
        ),
        migrations.AlterField(
            model_name='partnershiprequest',
            name='status',
            field=models.IntegerField(choices=[(0, '접수'), (1, '처리 중'), (2, '처리 완료')], default=0, help_text='제휴 문의에 대한 내부 처리 상태 관리용 상태입니다.', verbose_name='처리 상태'),
        ),
        migrations.CreateModel(
            name='ErrorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('title', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='접수된 오류 제보는 처리 상태 외의 정보 수정이 불가능합니다.', verbose_name='내용')),
                ('file', models.FileField(blank=True, help_text='접수된 오류 제보는 처리 상태 외의 정보 수정이 불가능합니다.', null=True, upload_to='', verbose_name='파일')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_request', to='book.book', verbose_name='도서')),
            ],
            options={
                'verbose_name': '오류 제보',
                'verbose_name_plural': '오류 제보',
            },
        ),
    ]
