# Generated by Django 4.0.6 on 2022-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_partnershiprequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorrequest',
            name='status',
            field=models.IntegerField(choices=[(0, '접수'), (1, '처리 중'), (2, '처리 완료')], default=0, help_text='오류 제보에 대한 내부 처리 상태 관리용 상태입니다.', verbose_name='처리 상태'),
        ),
    ]
