# Generated by Django 4.0.6 on 2022-07-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_pubdate'),
        ('board', '0007_errorrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorrequest',
            name='book',
            field=models.ForeignKey(help_text='접수된 오류 제보는 처리 상태 외의 정보 수정이 불가능합니다.', on_delete=django.db.models.deletion.CASCADE, related_name='error_request', to='book.book', verbose_name='도서'),
        ),
        migrations.AlterField(
            model_name='errorrequest',
            name='title',
            field=models.TextField(help_text='접수된 오류 제보는 처리 상태 외의 정보 수정이 불가능합니다.', verbose_name='제목'),
        ),
    ]
