# Generated by Django 4.0.6 on 2022-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_errorrequest_book_alter_errorrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('NOTICE', '공지사항'), ('FILE', '자료실'), ('ABOUT', '회사 소개'), ('CONTACT', '출간 문의')], max_length=10, verbose_name='유형'),
        ),
    ]
