# Generated by Django 4.0.6 on 2022-07-11 06:35

from django.db import migrations, models
import thebaeoom_backend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_board_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=thebaeoom_backend.utils.get_file_upload_path, verbose_name='첨부파일'),
        ),
    ]
