# Generated by Django 4.0.6 on 2022-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_board_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('NOTICE', '공지사항'), ('FILE', '자료실'), ('ABOUT', '회사 소개'), ('CONTACT', '출간 문의'), ('BRAND', '브랜드 소개'), ('MAP', '찾아오시는 길')], max_length=10, verbose_name='유형'),
        ),
    ]
